# This workflow automatically tests and builds new commits and pull requests as they come in.
name: Compile and test

on:
  push:
    paths:
    - 'src/**'
    - 'pom.xml'
    - '.github/workflows/maven.yml'

  pull_request:
    paths:
    - 'src/**'
    - 'pom.xml'

jobs:
  compile:
    name: Maven compiler
    runs-on: ubuntu-latest
    steps:

    # 1. Check out the current working tree
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Setup Java 25 JDK
    - name: Java 25 setup
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle' # Oracle 提供最新的 Java 25 早早期支持，也可尝试 'temurin'
        java-version: '25'

    # 3. Setup local Maven package cache to speed up building
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    # 4. Build via Maven 
    - name: Build via Maven
      run: mvn verify -B -Psql-tests --file pom.xml -DdisableXmlReport=true

    # 5. Upload built JAR files as Artifacts
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-java25
        path: |
          target/*.jar
          !target/*-sources.jar
